# Generated by Django 5.2.5 on 2025-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_otp_user_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryarea',
            name='area_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
