# Generated by Django 5.2.5 on 2025-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deliveryarea_area_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryarea',
            name='delivery_charge',
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='live_location',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
