# Generated by Django 5.2.5 on 2025-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_deliveryarea_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_areas',
            field=models.ManyToManyField(related_name='customers', to='main.deliveryarea'),
        ),
    ]
