# Generated by Django 5.2.5 on 2025-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_delivery_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryarea',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
